@host = 127.0.0.1
@port = 5001
@baseUri = http://{{host}}:{{port}}
@gqlUri = {{baseUri}}/graphql
@contentType = application/json
@requestType = GraphQL

### queryBooks
// @name queryBooks

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

query Books {
  books{
    id
    title
    author
    image
    description
    price
  }
}

### mutationCreateBook
// @name mutationCreateBook

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

mutation CreateBook($input: BookInput!) {
  createBook(input: $input) {
    id
    title
    author
    image
    description
    price
  }
}

{
  "input": {
  	"title": "Madness",
  	"author": "Koakh",
    "image": "https://i.pravatar.cc/150?img=14",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores nobis quae veniam, et iusto reiciendis",
    "price": 28.00
  }
}

### mutationUpdateBook
// @name mutationUpdateBook

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

mutation UpdateBook($id: ID!, $input: BookInput!) {
  updateBook(id: $id, input: $input) {
    id
    title
    author
    image
    description
    price
  }
}

{
  "id": 3,
  "input": {
    "title": "Koakh World*",
    "author": "Madness*",
    "image": "https://loremflickr.com/640/360",
    "description": "Curabitur vel lobortis nunc...*",
    "price": 14.28
  }
}

### mutationDeleteBook
// @name mutationDeleteBook

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

mutation DeleteBook($id: ID!) {
  deleteBook(id: $id) {
    id
    title
    author
    image
    description
    price
  }
}

{
  "id": 3
}

### mutationBroadcastRandomNumber
// @name mutationBroadcastRandomNumber

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

mutation BroadcastRandomNumber {
  broadcastRandomNumber
}

### subscriptionCountdown
// @name subscriptionCountdown

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

subscription Countdown {
  countdown(from: 999)
}

### subscriptionRandomNumber
// @name subscriptionRandomNumber

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

subscription RandomNumber {
  randomNumber
}

### subscriptionNewBooks
// @name subscriptionNewBooks

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

subscription NewBooks{
  newBooks{
    title
    author
  }
}
